### PR TITLE
Good first issues

### PR DESCRIPTION
**Pull request by TheWildHustle**
New features:
    
    - Users can now paste Npub as well as Hex formats. 
    - Nostr NIP-07 Login
    - Users can now download all avatar images in a zip file.
    - Optional image download
    - Calendar Date range selection 
    - User profile displays with banner and avatar.

---

1. Added new constants and variables:
    
    - `corsProxy` for handling CORS issues
    - `zapSendersResults` to store fetched zap senders data
2. New functions:
    
    - `convertToHexIfNpub`: Converts npub to hex format
    - `loadImage`: Loads images with CORS proxy
    - `downloadImageResult`: Creates and downloads a PNG image of the zap senders grid
    - `downloadAvatars`: Downloads all avatar images as a ZIP file
    - `login`: Handles user login with Nostr extension
    - `logout`: Handles user logout
    - `fetchUserProfile`: Fetches and displays user profile information
    - `updateLoginState`: Updates UI based on login state
3. Modified existing functions:
    
    - `getZapSenders`: Now uses a date range instead of a fixed time range
    - `fetchZapSenders`:
        - Now uses date range input instead of time range
        - Stores results in `zapSendersResults`
        - Shows/hides download buttons based on results
        - Displays user avatars and names in a grid
4. New UI elements and interactions:
    
    - Added date range picker (Flatpickr) for selecting zap time range
    - Added "Download Result as Image" button
    - Added "Download Avatars as ZIP" button
    - Added login/logout functionality
    - Added user profile display
5. Event listeners:
    
    - Added listeners for new buttons (download image, download avatars, login, logout)
6. Styling changes:
    
    - Added styles for user profile display
    - Updated styles for the zap senders grid
7. External libraries:
    
    - Added Flatpickr for date range selection
    - Added JSZip and FileSaver for ZIP file creation and download
8. Error handling:
    
    - Improved error handling and messaging throughout the script
9. CORS handling:
    
    - Implemented CORS proxy for loading images from various sources
10. Code structure:
    
    - Reorganized code for better readability and maintainability
    - Implemented more modular approach with separate functions for different features

Logged Out
image

Logged In
image

### CODE REVIEW

**Comment by bitkarrot** [comment]
Not sure if you need me to look at previous PRs, just this branch appears like this on firefox
A few notes: 

- Can we please revert back to dark mode instead of white background. 
- Download as image working, placeholders render as oval
- Download html or zip not working. (oddly zip download works on logout of profile, might just have taken a while? )

## White on white text rendering
Screenshot 2024-08-18 at 2 27 08 AM



## downloaded image - placeholders oddly in oval shape

Screenshot 2024-08-18 at 2 49 24 AM

**Comment by bitkarrot** [comment]
Sharp module missing in package.json, added to this branch

**Comment by TheWildHustle** [comment]
> Not sure if you need me to look at previous PRs, just this branch appears like this on firefox A few notes:
> 
> * Can we please revert back to dark mode instead of white background.
> * Download as image working, placeholders render as oval
> * Download html or zip not working. (oddly zip download works on logout of profile, might just have taken a while? )

- Darkmode enabled
- Download image working (Default avatar changed, still apears ovaled but looks a bit better)
zaplist_result (12)

- Download html working

**Comment by bitkarrot** [comment]
ok gonna try to squeeze in time and test this today.

**Comment by bitkarrot** [comment]
Looks grrrrreat! merging in. 

open issues we can leave: 
- oval images
- an option to add html file with local file referenced to the zip file

**Pull request merged**
